services:
  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_URL_WITH_SCHEMA: ${DATABASE_URL_WITH_SCHEMA}
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: prac
    command: --default-authentication-plugin=mysql_native_password