services:
  nginx:
    build:
      dockerfile: Dockerfile.nginx
    ports:
      - "80:8080"
  web:
    restart: always

#   db:
#     restart: always
#     volumes:
#       - prac-prod:/var/lib/mysql
# volumes:
#   prac-prod:
